name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [ 18.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Debug file structure
        run: find src/widgets

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build project
        run: npm run build:prod

      - name: Linting ts
        run: npm run lint:ts
    
      - name: Linting scss
        run: npm run lint:scss

      - name: unit test
        run: npm run unit

      - name: build storybook
        run: npm run build:storybook

      - name: screenshot test
        run: npm run test:ui:ci